# -*- coding: utf-8 -*-
"""DAA pt12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RJ9Hpn_SgiMedl9KS8-492G3yYuJyWEl
"""

pip install networkx

"""Pengukuran Centrality: EigenVector"""

import networkx as nx
import matplotlib.pyplot as plt

vertices = range(1,10)
edges = [(7,2), (2,3), (7,4), (4,5), (7,3), (7,5), (1,6), (1,7), (2,8), (2,9)]
G = nx.Graph()
G.add_nodes_from(vertices)
G.add_edges_from(edges)
nx.draw(G, with_labels=True,node_color='g',node_size=800)

"""Pengukuran degree centrality"""

nx.degree_centrality(G)

"""pengukuran betweenness centrality"""

nx.betweenness_centrality(G)

"""pengukuran closeness centrality"""

nx.closeness_centrality(G)

"""pengukuran eigenvector centrality"""

centrality = nx.eigenvector_centrality(G)

sorted((v, '{:0.2f}'.format(c)) for v, c in centrality.items())

"""Latihan"""

import networkx as nx
import matplotlib.pyplot as plt

vertices = range(1,10)
edges = [("Allen","Lisa"), ("Allen","Liz"), ("Liz","Emma"), ("Emma","Shane"), ("Shane","Liz"), ("Shane","Leah"), ("Leah","John"), ("John","Bob"), ("Bob","Mike"), ("Emma","Mike"), ("Shane","Leah"), ("Jill","Shane"), ("Mike","Jill"), ("Emma","Jill"), ("Leah","Jill"), ("John","Jill"), ("Bob","Jill"), ("Bob","Emma"), ("John","Shane")]
G = nx.Graph()
G.add_edges_from(edges)
nx.draw(G, with_labels=True,node_color='g',node_size=800)

nx.degree_centrality(G)

nx.betweenness_centrality(G)

nx.closeness_centrality(G)

centrality = nx.eigenvector_centrality(G)

sorted((v, '{:0.2f}'.format(c)) for v, c in centrality.items())

"""Latihan"""

import networkx as nx
import matplotlib.pyplot as plt

vertices = range(1,15)
edges = [(1,4), (1,10), (2,1), (2,12), (2,11), (2,15), (6,2), (6,9), (6,7), (6,14), (6,8), (3,2), (3,13), (3,5)]
G = nx.Graph()
G.add_nodes_from(vertices)
G.add_edges_from(edges)
nx.draw(G, with_labels=True,node_color='g',node_size=800)

nx.degree_centrality(G)

nx.betweenness_centrality(G)

nx.closeness_centrality(G)

centrality = nx.eigenvector_centrality(G)

sorted((v, '{:0.2f}'.format(c)) for v, c in centrality.items())

G_fb = nx.read_edgelist("/content/drive/MyDrive/Colab Notebooks/facebook_combined.txt.gz", create_using=nx.Graph(), nodetype=int)

print(nx.info(G_fb))

pos = nx.spring_layout(G_fb)
betCent = nx.betweenness_centrality(G_fb, normalized=True, endpoints=True)
node_Color = [20000.0 * G_fb.degree(v) for v in G_fb]
node_size = [v * 10000 for v in betCent.values()]
plt.figure(figsize=(20,20))
nx.draw_networkx(G_fb, pos=pos, with_labels=False,
                 node_Color=node_Color,
                 node_size=node_size )
plt.axis('off')